defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "James Daly"

title: mrvs
author: James Daly
email: hello@mrvs.city
description: >
  Student, outreach ambassador and developer. Consistency, accessibility and utility.

twitter_username: jda0_
github_username: jda0
facebook_username: 0jda0
instagram_username: jda0
linkedin_username: 0jda0
disqus:
  shortname: jda0

permalink: :categories/:short_year:month/:title

plugins:
  - jekyll-pwa-plugin

pwa:
  dest_js_directory: assets/js
  cache_name: pwa-cache
  precache_glob_directory: /
  precache_glob_patterns:
    - "assets/**/*.{js,css,svg,ttf,woff,woff2}"
    - "apps/*.html"
    - "/*.html"
  precache_glob_ignores:
    - sw-register.js